name: hall_of_fame
description: The HOF client (mainly for Android) written by Flutter with Material Design styles.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.4
  provider: 6.0.3
  shared_preferences: 2.0.15
  cached_network_image: 3.2.1
  flutter_staggered_grid_view: 0.6.1
  path_provider: 2.0.11
  share_plus: 4.0.8
  settings_ui: 2.0.2
  url_launcher: 6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

