name: Build and Deploy
on: [push]

# on: 
#   push:
#     tags:
#       - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop
      - run: flutter doctor -v
      - run: sudo apt install ninja-build
      - run: flutter doctor -v
      - run: flutter build linux
  


