name: Build and Deploy
on: [push]

# on: 
#   push:
#     tags:
#       - '*'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.2'
    - run: flutter config --enable-macos-desktop
    - run: flutter pub get
    - run: flutter build macos
    - run: cd build/macos/Build/Products/Release && ls -l
    - uses: actions/upload-artifact@v2
      with:
        name: macos.app
        path: build/macos/Build/Products/Release/hall_of_fame.app

